[package]
name = "inbrisk-policy"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
inbrisk-core.workspace = true
inbrisk-protocol.workspace = true
inbrisk-win32.workspace = true
serde.workspace = true
thiserror.workspace = true
parking_lot.workspace = true

[target.'cfg(windows)'.dependencies]
windows.workspace = true
