using System;
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using Inbrisk.Core;

namespace Inbrisk.Runtime;

#region Keyboard Event Contracts

/// <summary>
/// Type of keyboard event forwarded to Ghost Session 2.
/// </summary>
public enum GhostKeyEventKind
{
    /// <summary>Key pressed down (WM_KEYDOWN / WM_SYSKEYDOWN).</summary>
    KeyDown,

    /// <summary>Key released up (WM_KEYUP / WM_SYSKEYUP).</summary>
    KeyUp,

    /// <summary>Unicode character generated by keyboard input (WM_CHAR / WM_SYSCHAR).</summary>
    Char
}

/// <summary>
/// Cross-session payload carrying keyboard events from Host PiP to Session 2.
/// </summary>
public sealed record GhostKeyboardPayload
{
    [JsonPropertyName("event")]
    public string Event { get; init; } = string.Empty;

    [JsonPropertyName("vk")]
    public int VirtualKey { get; init; }

    [JsonPropertyName("scan")]
    public int ScanCode { get; init; }

    [JsonPropertyName("char")]
    public string? Character { get; init; }

    [JsonPropertyName("extended")]
    public bool Extended { get; init; }

    [JsonPropertyName("alt")]
    public bool Alt { get; init; }

    [JsonPropertyName("ctrl")]
    public bool Ctrl { get; init; }

    [JsonPropertyName("shift")]
    public bool Shift { get; init; }

    [JsonPropertyName("timestamp")]
    public long TimestampTicks { get; init; } = DateTime.UtcNow.Ticks;
}

#endregion

/// <summary>
/// High-speed Keyboard Forwarder and Global Hotkey Listener service.
/// Intercepts WM_KEYDOWN, WM_KEYUP, and WM_CHAR messages when the PiP window is focused
/// in interactive mode, and forwards Unicode characters and virtual key codes to Session 2
/// across the Ghost IPC bus.
/// Manages global hotkeys (RegisterHotKey):
/// - Ctrl + Alt + I: Toggle interactive mode (quick user intervention)
/// - Ctrl + Shift + P: Toggle PiP window visibility (hide / show)
/// - Esc: If fullscreen, restore back to mini PiP box
/// </summary>
public sealed class GhostKeyboardForwarder : IDisposable
{
    #region Win32 Constants & Interop

    private const int SW_HIDE = 0;
    private const int SW_SHOWNOACTIVATE = 4;
    private const int SW_SHOWNA = 8;

    private const uint SWP_NOSIZE = 0x0001;
    private const uint SWP_NOMOVE = 0x0002;
    private const uint SWP_NOACTIVATE = 0x0010;
    private const uint SWP_SHOWWINDOW = 0x0040;
    private static readonly IntPtr HwndTopmost = new(-1);
    private static readonly IntPtr HwndMessage = new(-3);

    private const uint WM_DESTROY = 0x0002;
    private const uint WM_QUIT = 0x0012;
    private const uint WM_KEYDOWN = 0x0100;
    private const uint WM_KEYUP = 0x0101;
    private const uint WM_CHAR = 0x0102;
    private const uint WM_SYSKEYDOWN = 0x0104;
    private const uint WM_SYSKEYUP = 0x0105;
    private const uint WM_SYSCHAR = 0x0106;
    private const uint WM_HOTKEY = 0x0312;

    public const uint MOD_ALT = 0x0001;
    public const uint MOD_CONTROL = 0x0002;
    public const uint MOD_SHIFT = 0x0004;
    public const uint MOD_WIN = 0x0008;
    public const uint MOD_NOREPEAT = 0x4000;

    public const int VK_ESCAPE = 0x1B;
    public const int VK_I = 0x49;
    public const int VK_P = 0x50;

    public const int SM_CXSCREEN = 0;
    public const int SM_CYSCREEN = 1;
    private const int GWL_EXSTYLE = -20;
    private const uint WS_EX_TRANSPARENT = 0x00000020;

    /// <summary>Hotkey ID for Ctrl + Alt + I (Toggle interactive mode).</summary>
    public const int HotKeyToggleInteractiveId = 0x1B8A01;

    /// <summary>Hotkey ID for Ctrl + Shift + P (Toggle visibility).</summary>
    public const int HotKeyToggleVisibilityId = 0x1B8A02;

    /// <summary>Hotkey ID for Esc (Exit fullscreen mode).</summary>
    public const int HotKeyEscapeFullscreenId = 0x1B8A03;

    private const string ListenerWindowClass = "InbriskHotkeyListenerWindowClass";

    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    private struct WNDCLASSEXW
    {
        public uint cbSize;
        public uint style;
        public IntPtr lpfnWndProc;
        public int cbClsExtra;
        public int cbWndExtra;
        public IntPtr hInstance;
        public IntPtr hIcon;
        public IntPtr hCursor;
        public IntPtr hbrBackground;
        public string? lpszMenuName;
        public string lpszClassName;
        public IntPtr hIconSm;
    }

    [StructLayout(LayoutKind.Sequential)]
    private struct MSG
    {
        public IntPtr hwnd;
        public uint message;
        public IntPtr wParam;
        public IntPtr lParam;
        public uint time;
        public int ptX;
        public int ptY;
    }

    [StructLayout(LayoutKind.Sequential)]
    private struct RECT
    {
        public int Left;
        public int Top;
        public int Right;
        public int Bottom;
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate IntPtr WndProcDelegate(IntPtr hwnd, uint msg, IntPtr wParam, IntPtr lParam);

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate IntPtr SubclassProc(IntPtr hWnd, uint uMsg, IntPtr wParam, IntPtr lParam, UIntPtr uIdSubclass, IntPtr dwRefData);

    private static class Win32
    {
        [DllImport("user32.dll", SetLastError = true)]
        public static extern bool RegisterHotKey(IntPtr hWnd, int id, uint fsModifiers, uint vk);

        [DllImport("user32.dll", SetLastError = true)]
        public static extern bool UnregisterHotKey(IntPtr hWnd, int id);

        [DllImport("user32.dll", SetLastError = true, CharSet = CharSet.Unicode)]
        public static extern ushort RegisterClassExW(ref WNDCLASSEXW lpwcx);

        [DllImport("user32.dll", SetLastError = true, CharSet = CharSet.Unicode)]
        public static extern IntPtr CreateWindowExW(
            uint dwExStyle,
            string lpClassName,
            string lpWindowName,
            uint dwStyle,
            int x, int y, int nWidth, int nHeight,
            IntPtr hWndParent, IntPtr hMenu, IntPtr hInstance, IntPtr lpParam);

        [DllImport("user32.dll", SetLastError = true)]
        public static extern bool DestroyWindow(IntPtr hWnd);

        [DllImport("user32.dll")]
        public static extern IntPtr DefWindowProcW(IntPtr hWnd, uint msg, IntPtr wParam, IntPtr lParam);

        [DllImport("user32.dll")]
        public static extern int GetMessageW(out MSG lpMsg, IntPtr hWnd, uint wMsgFilterMin, uint wMsgFilterMax);

        [DllImport("user32.dll")]
        public static extern bool TranslateMessage(ref MSG lpMsg);

        [DllImport("user32.dll")]
        public static extern IntPtr DispatchMessageW(ref MSG lpMsg);

        [DllImport("user32.dll")]
        public static extern bool PostMessageW(IntPtr hWnd, uint msg, IntPtr wParam, IntPtr lParam);

        [DllImport("user32.dll")]
        public static extern bool PostThreadMessageW(uint idThread, uint msg, IntPtr wParam, IntPtr lParam);

        [DllImport("kernel32.dll")]
        public static extern uint GetCurrentThreadId();

        [DllImport("kernel32.dll", CharSet = CharSet.Unicode)]
        public static extern IntPtr GetModuleHandleW(string? lpModuleName);

        [DllImport("user32.dll")]
        public static extern bool ShowWindow(IntPtr hWnd, int nCmdShow);

        [DllImport("user32.dll")]
        public static extern bool IsWindowVisible(IntPtr hWnd);

        [DllImport("user32.dll")]
        public static extern IntPtr GetForegroundWindow();

        [DllImport("user32.dll", SetLastError = true)]
        public static extern bool SetWindowPos(IntPtr hWnd, IntPtr hWndInsertAfter, int X, int Y, int cx, int cy, uint uFlags);

        [DllImport("user32.dll", SetLastError = true)]
        public static extern bool GetWindowRect(IntPtr hWnd, out RECT lpRect);

        [DllImport("user32.dll")]
        public static extern int GetSystemMetrics(int nIndex);

        [DllImport("user32.dll", EntryPoint = "GetWindowLongPtrW")]
        public static extern IntPtr GetWindowLongPtr64(IntPtr hWnd, int nIndex);

        [DllImport("user32.dll", EntryPoint = "SetWindowLongPtrW")]
        public static extern IntPtr SetWindowLongPtr64(IntPtr hWnd, int nIndex, IntPtr dwNewLong);

        [DllImport("comctl32.dll", SetLastError = true)]
        public static extern bool SetWindowSubclass(IntPtr hWnd, SubclassProc pfnSubclass, UIntPtr uIdSubclass, IntPtr dwRefData);

        [DllImport("comctl32.dll", SetLastError = true)]
        public static extern bool RemoveWindowSubclass(IntPtr hWnd, SubclassProc pfnSubclass, UIntPtr uIdSubclass);

        [DllImport("comctl32.dll")]
        public static extern IntPtr DefSubclassProc(IntPtr hWnd, uint uMsg, IntPtr wParam, IntPtr lParam);

        [DllImport("user32.dll")]
        public static extern short GetKeyState(int nVirtKey);
    }

    #endregion

    #region State & Fields

    private static readonly object ClassLock = new();
    private static bool _classRegistered;
    private static WndProcDelegate? _staticWndProc;

    private readonly object _gate = new();
    private readonly ManualResetEventSlim _listenerReady = new();

    private IGhostIpcBus? _ipcBus;
    private GhostPipManager? _pipManager;
    private IntPtr _targetHwnd = IntPtr.Zero;

    private Thread? _listenerThread;
    private uint _listenerThreadId;
    private IntPtr _listenerHwnd = IntPtr.Zero;

    private SubclassProc? _subclassDelegate;
    private IntPtr _subclassedHwnd = IntPtr.Zero;
    private static readonly UIntPtr SubclassId = new(0x1B8A);

    private volatile bool _isInteractive;
    private volatile bool _forwardingEnabled = true;
    private volatile bool _isFullscreen;
    private volatile bool _registerEscOnlyWhenFullscreen = true;
    private volatile bool _isListening;
    private volatile bool _disposed;

    private (int X, int Y, int Width, int Height)? _savedBounds;

    #endregion

    #region Events

    /// <summary>Raised when interactive mode is toggled (e.g. via Ctrl+Alt+I).</summary>
    public event Action<bool>? InteractiveModeToggled;

    /// <summary>Raised when PiP window visibility is toggled (e.g. via Ctrl+Shift+P).</summary>
    public event Action<bool>? VisibilityToggled;

    /// <summary>Raised when fullscreen state changes.</summary>
    public event Action<bool>? FullscreenChanged;

    /// <summary>Raised when Esc is pressed in fullscreen mode requesting exit back to mini PiP.</summary>
    public event Action? FullscreenExitRequested;

    /// <summary>Raised when Esc key is pressed.</summary>
    public event Action? EscapePressed;

    /// <summary>Raised whenever a global hotkey is triggered.</summary>
    public event Action<int>? HotKeyPressed;

    /// <summary>Raised when a keyboard event has been successfully forwarded to Session 2.</summary>
    public event Action<GhostKeyboardPayload>? KeyForwarded;

    /// <summary>Raised when an error occurs during IPC key forwarding.</summary>
    public event Action<Exception>? ForwardingError;

    #endregion

    #region Properties

    /// <summary>Gets or sets the IPC bus used to dispatch keyboard events to Session 2.</summary>
    public IGhostIpcBus? IpcBus
    {
        get => _ipcBus;
        set => _ipcBus = value;
    }

    /// <summary>Gets or sets the associated PiP manager instance.</summary>
    public GhostPipManager? PipManager
    {
        get => _pipManager;
        set
        {
            _pipManager = value;
            if (_pipManager != null && _targetHwnd == IntPtr.Zero)
            {
                _targetHwnd = _pipManager.WindowHandle;
            }
        }
    }

    /// <summary>Gets or sets the target PiP native window handle.</summary>
    public IntPtr TargetHwnd
    {
        get => _targetHwnd != IntPtr.Zero ? _targetHwnd : (_pipManager?.WindowHandle ?? IntPtr.Zero);
        set
        {
            if (_targetHwnd != value)
            {
                DetachWindowSubclass();
                _targetHwnd = value;
                if (value != IntPtr.Zero && _isListening)
                {
                    AttachWindowSubclass(value);
                }
            }
        }
    }

    /// <summary>Gets whether interactive mode is currently active.</summary>
    public bool IsInteractive => _pipManager?.IsInteractive ?? _isInteractive;

    /// <summary>Gets whether the background hotkey listener is active.</summary>
    public bool IsListening => _isListening;

    /// <summary>Gets whether the PiP window is currently expanded to fullscreen.</summary>
    public bool IsFullscreen => _isFullscreen;

    /// <summary>Gets or sets whether keyboard forwarding to Session 2 is currently enabled.</summary>
    public bool ForwardingEnabled
    {
        get => _forwardingEnabled;
        set => _forwardingEnabled = value;
    }

    /// <summary>
    /// Gets or sets whether the global Esc hotkey is registered only during fullscreen mode (default: true).
    /// Prevents hijacking the user's Esc key in other applications when PiP is running in mini box mode.
    /// </summary>
    public bool RegisterEscOnlyWhenFullscreen
    {
        get => _registerEscOnlyWhenFullscreen;
        set
        {
            _registerEscOnlyWhenFullscreen = value;
            UpdateEscHotkeyRegistration();
        }
    }

    #endregion

    #region Constructors

    /// <summary>
    /// Initializes a new instance of the <see cref="GhostKeyboardForwarder"/> class.
    /// </summary>
    public GhostKeyboardForwarder()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="GhostKeyboardForwarder"/> class with specified IPC bus and PiP manager.
    /// </summary>
    public GhostKeyboardForwarder(
        IGhostIpcBus? ipcBus,
        GhostPipManager? pipManager = null,
        IntPtr targetHwnd = default,
        bool autoStart = true)
    {
        _ipcBus = ipcBus;
        _pipManager = pipManager;
        _targetHwnd = targetHwnd != IntPtr.Zero ? targetHwnd : (pipManager?.WindowHandle ?? IntPtr.Zero);

        if (autoStart)
        {
            Start();
        }
    }

    #endregion

    #region Lifecycle & Start / Stop

    /// <summary>
    /// Starts the dedicated background hotkey listener and attaches to the target PiP window if present.
    /// </summary>
    public void Start(int timeoutMs = 5000)
    {
        lock (_gate)
        {
            if (_disposed) throw new ObjectDisposedException(nameof(GhostKeyboardForwarder));
            if (_isListening) return;

            if (OperatingSystem.IsWindows())
            {
                _listenerReady.Reset();
                _listenerThread = new Thread(ListenerPump)
                {
                    IsBackground = true,
                    Name = "InbriskGhostHotkeyListener"
                };
                _listenerThread.SetApartmentState(ApartmentState.STA);
                _listenerThread.Start();

                _listenerReady.Wait(timeoutMs);

                var effectiveHwnd = TargetHwnd;
                if (effectiveHwnd != IntPtr.Zero)
                {
                    AttachWindowSubclass(effectiveHwnd);
                }
            }

            _isListening = true;
        }
    }

    /// <summary>
    /// Stops the hotkey listener and cleans up native hooks and window subclasses.
    /// </summary>
    public void Stop()
    {
        lock (_gate)
        {
            if (!_isListening) return;

            DetachWindowSubclass();

            if (_listenerHwnd != IntPtr.Zero)
            {
                UnregisterAllHotkeys();
            }

            if (_listenerThreadId != 0)
            {
                Win32.PostThreadMessageW(_listenerThreadId, WM_QUIT, IntPtr.Zero, IntPtr.Zero);
                _listenerThread?.Join(1500);
                _listenerThread = null;
                _listenerThreadId = 0;
            }

            _isListening = false;
        }
    }

    #endregion

    #region Hotkey Registration & Listener Message Loop

    private void ListenerPump()
    {
        try
        {
            _listenerThreadId = Win32.GetCurrentThreadId();
            EnsureListenerClassRegistered();

            _listenerHwnd = Win32.CreateWindowExW(
                0,
                ListenerWindowClass,
                "InbriskHotkeyListener",
                0,
                0, 0, 0, 0,
                HwndMessage,
                IntPtr.Zero,
                Win32.GetModuleHandleW(null),
                IntPtr.Zero);

            RegisterDefaultHotkeys();
        }
        catch (Exception ex)
        {
            Debug.WriteLine($"[GhostKeyboardForwarder] ListenerPump init fault: {ex.Message}");
        }
        finally
        {
            _listenerReady.Set();
        }

        while (Win32.GetMessageW(out var msg, IntPtr.Zero, 0, 0) > 0)
        {
            try
            {
                if (msg.message == WM_HOTKEY)
                {
                    HandleHotKey(msg.wParam.ToInt32());
                }

                Win32.TranslateMessage(ref msg);
                Win32.DispatchMessageW(ref msg);
            }
            catch (Exception ex)
            {
                Debug.WriteLine($"[GhostKeyboardForwarder] Pump message loop exception: {ex.Message}");
            }
        }

        if (_listenerHwnd != IntPtr.Zero)
        {
            UnregisterAllHotkeys();
            Win32.DestroyWindow(_listenerHwnd);
            _listenerHwnd = IntPtr.Zero;
        }
    }

    private static void EnsureListenerClassRegistered()
    {
        lock (ClassLock)
        {
            if (_classRegistered) return;

            _staticWndProc = (hwnd, msg, wParam, lParam) =>
            {
                return Win32.DefWindowProcW(hwnd, msg, wParam, lParam);
            };

            var wc = new WNDCLASSEXW
            {
                cbSize = (uint)Marshal.SizeOf<WNDCLASSEXW>(),
                style = 0,
                lpfnWndProc = Marshal.GetFunctionPointerForDelegate(_staticWndProc),
                cbClsExtra = 0,
                cbWndExtra = 0,
                hInstance = Win32.GetModuleHandleW(null),
                hIcon = IntPtr.Zero,
                hCursor = IntPtr.Zero,
                hbrBackground = IntPtr.Zero,
                lpszMenuName = null,
                lpszClassName = ListenerWindowClass,
                hIconSm = IntPtr.Zero
            };

            Win32.RegisterClassExW(ref wc);
            _classRegistered = true;
        }
    }

    private void RegisterDefaultHotkeys()
    {
        if (_listenerHwnd == IntPtr.Zero || !OperatingSystem.IsWindows()) return;

        // 1. Ctrl + Alt + I -> Toggle Interactive mode
        bool okInteractive = Win32.RegisterHotKey(
            _listenerHwnd,
            HotKeyToggleInteractiveId,
            MOD_CONTROL | MOD_ALT | MOD_NOREPEAT,
            VK_I);

        if (!okInteractive)
        {
            Debug.WriteLine("[GhostKeyboardForwarder] Warning: Failed to register hotkey Ctrl+Alt+I.");
        }

        // 2. Ctrl + Shift + P -> Toggle PiP visibility
        bool okVisibility = Win32.RegisterHotKey(
            _listenerHwnd,
            HotKeyToggleVisibilityId,
            MOD_CONTROL | MOD_SHIFT | MOD_NOREPEAT,
            VK_P);

        if (!okVisibility)
        {
            Debug.WriteLine("[GhostKeyboardForwarder] Warning: Failed to register hotkey Ctrl+Shift+P.");
        }

        // 3. Esc -> Exit fullscreen (conditional on fullscreen or user setting)
        UpdateEscHotkeyRegistration();
    }

    private void UpdateEscHotkeyRegistration()
    {
        if (_listenerHwnd == IntPtr.Zero || !OperatingSystem.IsWindows()) return;

        bool shouldRegisterEsc = !_registerEscOnlyWhenFullscreen || _isFullscreen;
        if (shouldRegisterEsc)
        {
            Win32.RegisterHotKey(
                _listenerHwnd,
                HotKeyEscapeFullscreenId,
                MOD_NOREPEAT,
                VK_ESCAPE);
        }
        else
        {
            Win32.UnregisterHotKey(_listenerHwnd, HotKeyEscapeFullscreenId);
        }
    }

    private void UnregisterAllHotkeys()
    {
        if (_listenerHwnd == IntPtr.Zero || !OperatingSystem.IsWindows()) return;

        Win32.UnregisterHotKey(_listenerHwnd, HotKeyToggleInteractiveId);
        Win32.UnregisterHotKey(_listenerHwnd, HotKeyToggleVisibilityId);
        Win32.UnregisterHotKey(_listenerHwnd, HotKeyEscapeFullscreenId);
    }

    private void HandleHotKey(int id)
    {
        HotKeyPressed?.Invoke(id);

        switch (id)
        {
            case HotKeyToggleInteractiveId:
                ToggleInteractive();
                break;

            case HotKeyToggleVisibilityId:
                ToggleVisibility();
                break;

            case HotKeyEscapeFullscreenId:
                HandleEscape();
                break;
        }
    }

    #endregion

    #region Window Subclassing (Focus & Key Capture)

    /// <summary>
    /// Attaches to a PiP native window handle to capture WM_KEYDOWN, WM_KEYUP, and WM_CHAR messages.
    /// </summary>
    public void AttachToWindow(IntPtr hwnd)
    {
        if (hwnd == IntPtr.Zero || !OperatingSystem.IsWindows()) return;
        lock (_gate)
        {
            _targetHwnd = hwnd;
            AttachWindowSubclass(hwnd);
        }
    }

    private void AttachWindowSubclass(IntPtr hwnd)
    {
        if (hwnd == IntPtr.Zero || !OperatingSystem.IsWindows()) return;

        try
        {
            DetachWindowSubclass();

            _subclassDelegate = SubclassWindowProc;
            bool ok = Win32.SetWindowSubclass(hwnd, _subclassDelegate, SubclassId, IntPtr.Zero);
            if (ok)
            {
                _subclassedHwnd = hwnd;
            }
            else
            {
                Debug.WriteLine($"[GhostKeyboardForwarder] SetWindowSubclass failed for HWND 0x{hwnd:X}");
            }
        }
        catch (Exception ex)
        {
            Debug.WriteLine($"[GhostKeyboardForwarder] Failed to attach subclass: {ex.Message}");
        }
    }

    private void DetachWindowSubclass()
    {
        if (_subclassedHwnd != IntPtr.Zero && _subclassDelegate != null && OperatingSystem.IsWindows())
        {
            try
            {
                Win32.RemoveWindowSubclass(_subclassedHwnd, _subclassDelegate, SubclassId);
            }
            catch { }
            _subclassedHwnd = IntPtr.Zero;
        }
    }

    private IntPtr SubclassWindowProc(IntPtr hWnd, uint uMsg, IntPtr wParam, IntPtr lParam, UIntPtr uIdSubclass, IntPtr dwRefData)
    {
        if (ProcessWindowMessage(hWnd, uMsg, wParam, lParam, out bool handled))
        {
            if (handled)
            {
                return IntPtr.Zero;
            }
        }

        return Win32.DefSubclassProc(hWnd, uMsg, wParam, lParam);
    }

    #endregion

    #region Window Message Processing

    /// <summary>
    /// Manually feeds a Win32 window message into the keyboard forwarder.
    /// Useful if integrating directly into an existing WndProc loop.
    /// </summary>
    public bool ProcessWindowMessage(IntPtr hwnd, uint msg, IntPtr wParam, IntPtr lParam, out bool handled)
    {
        handled = false;

        switch (msg)
        {
            case WM_KEYDOWN:
            case WM_SYSKEYDOWN:
            {
                int vk = (int)wParam;
                long lp = lParam.ToInt64();
                int scan = (int)((lp >> 16) & 0xFF);
                bool extended = (lp & (1 << 24)) != 0;
                bool alt = (lp & (1 << 29)) != 0;
                bool ctrl = (Win32.GetKeyState(0x11) & 0x8000) != 0;
                bool shift = (Win32.GetKeyState(0x10) & 0x8000) != 0;

                // Escape key in fullscreen mode triggers exit to mini box
                if (vk == VK_ESCAPE && _isFullscreen)
                {
                    HandleEscape();
                    handled = true;
                    return true;
                }

                if (IsInteractive && _forwardingEnabled)
                {
                    _ = ForwardKeyAsync(GhostKeyEventKind.KeyDown, vk, scan, extended, alt, ctrl, shift);
                    handled = true;
                }
                return true;
            }

            case WM_KEYUP:
            case WM_SYSKEYUP:
            {
                int vk = (int)wParam;
                long lp = lParam.ToInt64();
                int scan = (int)((lp >> 16) & 0xFF);
                bool extended = (lp & (1 << 24)) != 0;
                bool alt = (lp & (1 << 29)) != 0;
                bool ctrl = (Win32.GetKeyState(0x11) & 0x8000) != 0;
                bool shift = (Win32.GetKeyState(0x10) & 0x8000) != 0;

                if (IsInteractive && _forwardingEnabled)
                {
                    _ = ForwardKeyAsync(GhostKeyEventKind.KeyUp, vk, scan, extended, alt, ctrl, shift);
                    handled = true;
                }
                return true;
            }

            case WM_CHAR:
            case WM_SYSCHAR:
            {
                char c = (char)wParam;

                if (IsInteractive && _forwardingEnabled)
                {
                    _ = ForwardCharAsync(c);
                    handled = true;
                }
                return true;
            }

            case WM_HOTKEY:
            {
                HandleHotKey(wParam.ToInt32());
                handled = true;
                return true;
            }
        }

        return false;
    }

    #endregion

    #region Forwarding Logic (IPC to Session 2)

    /// <summary>
    /// Forwards a key press or release event across the Ghost IPC bus to Session 2.
    /// </summary>
    public async Task<bool> ForwardKeyAsync(
        GhostKeyEventKind kind,
        int virtualKey,
        int scanCode = 0,
        bool isExtended = false,
        bool alt = false,
        bool ctrl = false,
        bool shift = false,
        CancellationToken ct = default)
    {
        var payload = new GhostKeyboardPayload
        {
            Event = kind switch
            {
                GhostKeyEventKind.KeyDown => "keydown",
                GhostKeyEventKind.KeyUp => "keyup",
                GhostKeyEventKind.Char => "char",
                _ => "keydown"
            },
            VirtualKey = virtualKey,
            ScanCode = scanCode,
            Extended = isExtended,
            Alt = alt,
            Ctrl = ctrl,
            Shift = shift,
            TimestampTicks = DateTime.UtcNow.Ticks
        };

        return await SendPayloadOverIpcAsync(payload, ct).ConfigureAwait(false);
    }

    /// <summary>
    /// Forwards a Unicode character generated by keyboard input to Session 2.
    /// </summary>
    public async Task<bool> ForwardCharAsync(char character, CancellationToken ct = default)
    {
        var payload = new GhostKeyboardPayload
        {
            Event = "char",
            Character = character.ToString(),
            VirtualKey = character,
            TimestampTicks = DateTime.UtcNow.Ticks
        };

        return await SendPayloadOverIpcAsync(payload, ct).ConfigureAwait(false);
    }

    /// <summary>
    /// Forwards text directly to the active application in Session 2.
    /// </summary>
    public async Task<bool> ForwardTextAsync(string text, CancellationToken ct = default)
    {
        if (string.IsNullOrEmpty(text)) return true;

        var payload = new GhostKeyboardPayload
        {
            Event = "type",
            Character = text,
            TimestampTicks = DateTime.UtcNow.Ticks
        };

        return await SendPayloadOverIpcAsync(payload, ct).ConfigureAwait(false);
    }

    private async Task<bool> SendPayloadOverIpcAsync(GhostKeyboardPayload payload, CancellationToken ct)
    {
        var bus = _ipcBus;
        if (bus == null || !bus.IsConnected)
        {
            return false;
        }

        string json = JsonSerializer.Serialize(payload);

        try
        {
            // 1. Primary: dedicated forward_keyboard action
            await bus.SendRequestAsync("forward_keyboard", json, TimeSpan.FromSeconds(2), ct).ConfigureAwait(false);
            KeyForwarded?.Invoke(payload);
            return true;
        }
        catch (GhostIpcException)
        {
            // 2. Fallback: format as execute_batch step for Session 2 daemons
            return await FallbackBatchForwardAsync(bus, payload, ct).ConfigureAwait(false);
        }
        catch (Exception ex)
        {
            Debug.WriteLine($"[GhostKeyboardForwarder] Forwarding error: {ex.Message}");
            ForwardingError?.Invoke(ex);
            return false;
        }
    }

    private async Task<bool> FallbackBatchForwardAsync(IGhostIpcBus bus, GhostKeyboardPayload payload, CancellationToken ct)
    {
        try
        {
            string? stepJson = null;

            if (payload.Event == "char" || payload.Event == "type" || !string.IsNullOrEmpty(payload.Character))
            {
                string text = payload.Character ?? string.Empty;
                stepJson = JsonSerializer.Serialize(new[]
                {
                    new { @do = "type", v = text }
                });
            }
            else if (payload.Event == "keydown")
            {
                string? keyName = VirtualKeyToKeyName(payload.VirtualKey);
                if (!string.IsNullOrEmpty(keyName))
                {
                    stepJson = JsonSerializer.Serialize(new[]
                    {
                        new { @do = "key", v = keyName }
                    });
                }
            }

            if (!string.IsNullOrEmpty(stepJson))
            {
                await bus.SendRequestAsync("execute_batch", stepJson, TimeSpan.FromSeconds(2), ct).ConfigureAwait(false);
                KeyForwarded?.Invoke(payload);
                return true;
            }
        }
        catch (Exception ex)
        {
            Debug.WriteLine($"[GhostKeyboardForwarder] Fallback batch error: {ex.Message}");
            ForwardingError?.Invoke(ex);
        }

        return false;
    }

    /// <summary>
    /// Translates a virtual key code into a friendly key identifier name.
    /// </summary>
    public static string? VirtualKeyToKeyName(int vk) => vk switch
    {
        0x08 => "Backspace",
        0x09 => "Tab",
        0x0D => "Enter",
        0x10 => "Shift",
        0x11 => "Ctrl",
        0x12 => "Alt",
        0x13 => "Pause",
        0x14 => "CapsLock",
        0x1B => "Escape",
        0x20 => "Space",
        0x21 => "PageUp",
        0x22 => "PageDown",
        0x23 => "End",
        0x24 => "Home",
        0x25 => "Left",
        0x26 => "Up",
        0x27 => "Right",
        0x28 => "Down",
        0x2C => "PrintScreen",
        0x2D => "Insert",
        0x2E => "Delete",
        >= 0x30 and <= 0x39 => ((char)vk).ToString(),
        >= 0x41 and <= 0x5A => ((char)vk).ToString(),
        >= 0x70 and <= 0x87 => $"F{vk - 0x70 + 1}",
        _ => null
    };

    #endregion

    #region Action Helpers (Interactive / Visibility / Fullscreen)

    /// <summary>
    /// Toggles interactive mode (WS_EX_TRANSPARENT click-through).
    /// </summary>
    public bool ToggleInteractive()
    {
        bool next = !IsInteractive;
        SetInteractive(next);
        return next;
    }

    /// <summary>
    /// Explicitly sets interactive mode.
    /// </summary>
    public void SetInteractive(bool interactive)
    {
        _isInteractive = interactive;

        if (_pipManager != null)
        {
            _pipManager.SetInteractive(interactive);
        }
        else
        {
            var hwnd = TargetHwnd;
            if (hwnd != IntPtr.Zero && OperatingSystem.IsWindows())
            {
                SetClickThrough(hwnd, !interactive);
            }
        }

        InteractiveModeToggled?.Invoke(interactive);
    }

    /// <summary>
    /// Toggles PiP window visibility (hide / show).
    /// </summary>
    public bool ToggleVisibility()
    {
        var hwnd = TargetHwnd;
        bool newVisible;

        if (hwnd != IntPtr.Zero && OperatingSystem.IsWindows())
        {
            bool cur = Win32.IsWindowVisible(hwnd);
            newVisible = !cur;
            Win32.ShowWindow(hwnd, newVisible ? SW_SHOWNA : SW_HIDE);
        }
        else
        {
            newVisible = true;
        }

        VisibilityToggled?.Invoke(newVisible);
        return newVisible;
    }

    /// <summary>
    /// Expands the PiP window to fill the entire primary screen.
    /// </summary>
    public void EnterFullscreen()
    {
        if (_isFullscreen) return;

        var hwnd = TargetHwnd;
        if (hwnd != IntPtr.Zero && OperatingSystem.IsWindows())
        {
            if (Win32.GetWindowRect(hwnd, out var rect))
            {
                _savedBounds = (rect.Left, rect.Top, rect.Right - rect.Left, rect.Bottom - rect.Top);
            }

            int cx = Win32.GetSystemMetrics(SM_CXSCREEN);
            int cy = Win32.GetSystemMetrics(SM_CYSCREEN);
            if (cx <= 0) cx = 1920;
            if (cy <= 0) cy = 1080;

            Win32.SetWindowPos(hwnd, HwndTopmost, 0, 0, cx, cy, SWP_NOACTIVATE | SWP_SHOWWINDOW);
        }

        _isFullscreen = true;
        UpdateEscHotkeyRegistration();
        FullscreenChanged?.Invoke(true);
    }

    /// <summary>
    /// Restores the PiP window from fullscreen back to its previous bounds or default mini box.
    /// </summary>
    public void ExitFullscreen()
    {
        if (!_isFullscreen) return;

        var hwnd = TargetHwnd;

        if (_pipManager != null)
        {
            _pipManager.SetScale(1.0f);
            _pipManager.SetPosition(PipPresetPosition.TopRight);
        }
        else if (hwnd != IntPtr.Zero && OperatingSystem.IsWindows())
        {
            int x = _savedBounds?.X ?? 100;
            int y = _savedBounds?.Y ?? 100;
            int w = _savedBounds?.Width ?? GhostPipManager.BaseWidth;
            int h = _savedBounds?.Height ?? GhostPipManager.BaseHeight;
            Win32.SetWindowPos(hwnd, HwndTopmost, x, y, w, h, SWP_NOACTIVATE | SWP_SHOWWINDOW);
        }

        _isFullscreen = false;
        UpdateEscHotkeyRegistration();
        FullscreenChanged?.Invoke(false);
        FullscreenExitRequested?.Invoke();
    }

    /// <summary>
    /// Handles the Escape key action.
    /// </summary>
    private void HandleEscape()
    {
        if (_isFullscreen)
        {
            ExitFullscreen();
        }
        else
        {
            EscapePressed?.Invoke();
        }
    }

    private static void SetClickThrough(IntPtr hwnd, bool clickThrough)
    {
        try
        {
            long cur = Win32.GetWindowLongPtr64(hwnd, GWL_EXSTYLE).ToInt64();
            long updated = clickThrough ? (cur | WS_EX_TRANSPARENT) : (cur & ~WS_EX_TRANSPARENT);
            if (cur != updated)
            {
                Win32.SetWindowLongPtr64(hwnd, GWL_EXSTYLE, new IntPtr(updated));
                Win32.SetWindowPos(hwnd, IntPtr.Zero, 0, 0, 0, 0, SWP_NOMOVE | SWP_NOSIZE | SWP_NOACTIVATE);
            }
        }
        catch { }
    }

    #endregion

    #region Fluent Configuration Helpers

    /// <summary>Attaches an IPC bus instance and returns this forwarder.</summary>
    public GhostKeyboardForwarder WithIpcBus(IGhostIpcBus bus)
    {
        IpcBus = bus;
        return this;
    }

    /// <summary>Attaches a GhostPipManager instance and returns this forwarder.</summary>
    public GhostKeyboardForwarder WithPipManager(GhostPipManager manager)
    {
        PipManager = manager;
        return this;
    }

    /// <summary>Attaches a target window handle and returns this forwarder.</summary>
    public GhostKeyboardForwarder WithTargetWindow(IntPtr hwnd)
    {
        TargetHwnd = hwnd;
        return this;
    }

    #endregion

    #region IDisposable

    /// <summary>
    /// Disposes resources, unregisters all global hotkeys, and detaches native window hooks.
    /// </summary>
    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;

        Stop();
        _listenerReady.Dispose();
        GC.SuppressFinalize(this);
    }

    #endregion
}
